<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class PublicController extends Controller
{
    public function send_otp(Request $request)
    {
        $user = User::where('email', $request->email)->get();

        if(count($user) == 0){
            return response()->json([
                'message' => 'No user with your email was found.'
            ]);
        }

        $user = $user[0];
        $otp = generate_otp();
        $user->otp = $otp;
        $user->save();

        Mail::raw('Your OTP is: ' . $otp, function($message) use($user) {
            $message->subject('SAT - One Time Password')->to($user->email);
        });


        return response()->json([
            'message' => 'OTP has been sent to '.$user->email.'.'
        ]);
    }

    public function verify_otp(Request  $request)
    {
        $user = User::where('email', $request->email)->where('otp', $request->otp)->get();

        if(count($user) == 0){
            return response()->json([
                'message' => 'Wrong OTP.'
            ]);
        }

        $user = $user[0];
        $user->otp = NULL;
        $user->save();

        return response()->json([
            'message' => 'OTP succesful.'
        ]);
    }

    public function get_civ_data(Request $request)
    {
        $token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6Ijg4YTQ0ZjYyNjZmNzlmMzc4OTZhMTViOTIzOWNlOTEwY2Y5Y2VhOWI4ZjM1NWE3MzZlZWZlZjVkYTFkMTk0NGFkNzNhNDFkZGM1NWJiZGU5In0.eyJhdWQiOiIxMSIsImp0aSI6Ijg4YTQ0ZjYyNjZmNzlmMzc4OTZhMTViOTIzOWNlOTEwY2Y5Y2VhOWI4ZjM1NWE3MzZlZWZlZjVkYTFkMTk0NGFkNzNhNDFkZGM1NWJiZGU5IiwiaWF0IjoxNjQ5MjgyOTQ4LCJuYmYiOjE2NDkyODI5NDgsImV4cCI6MTY4MDgxODk0OCwic3ViIjoiMjYxIiwic2NvcGVzIjpbXX0.Rf6g31d9brL0vdhfforL4JTHllO9zVeJQsgV646LBaw_P5IW5u4NJrHjCGsFUqb-gnpUuBY1QzPu9OIf-lJNvjNoG9gdmdoPhgAx14dFUBKFPEnbLSLFvv8Q3BAAuyf_Ks-aTlt3TSGIlF9lLjC4SebOCFEtN7WXjKerasjlLg52RuraOZfsI87XV9SVJnhMmqSZ2dUk3cglpvw6D6zr8KNmMUZguRw85-DfEfAev9T06rqQdNwWOc2WvPLePRX86XLOvVanpTI1BCipL9oV-di7yCEQFw7nXRtOyTuJaihfj_jh6od4ItC8aUXbVUXbgKtF4YsoZqMc8XY4c-ZXbbZfpWj_249hIKZqMefCqIB9qzXO_UnNlI-oRi5c90goyp65NY1mVrXb5J46-gNBkRR8Fv3VsDZHYK5Y4CskKAsUrzDjmVLRUDs405JDWPY2qTr0Tim4q_7iqoMjQKT-k_r05aPn6vp7fN76pkMtgpVMvkfrMmYBc79hOMP-8rK9TcIx8YAFuIC7fsbVyUh4QdavwALaT-OcfHcIueVy2zncvYwmGI5hoFBRGeOznUFDvsmxTsomVGhWInyM59ikwloz-EbIZCIfIdq2SUEn4RbOnTAsWnWdO8MJIpapw_UjQ3m4TagdWDYr7P8qS-lfYAA9aCur0OdXx-LIoFXECAI';
        $data = [

        ];
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://txa-clinic.taag-genetics.com/api/patient/v2/show?idp='.$request->idp.'&tipo_identificacion='.$request->tipo_identificacion);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

//        curl_setopt($ch, CURLOPT_POSTFIELDS, "[post data]");

        $headers = array();
        $headers[] = 'Authorization: Bearer ' . $token;
        $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return response()->json(json_decode($result));
    }
}
